### ISSUE TITLE
程序包com.fr.third.springframework.aop.framework不存在

### ISSUE THREAD

**Issue by Abbbbbqvq** [H4cking2theGate/Frchannel#1]
程序包com.fr.third.springframework.aop.framework不存在
<img width="1547" alt="image" src="https://github.com/user-attachments/assets/0a1f3b94-86f4-4ec4-bc72-62720c864a72">

**Comment by H4cking2theGate** [comment]
编译用jdk，需要添加lib中的依赖

**Comment by H4cking2theGate** [comment]
jdk8
